# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o9mmrEjMvE982iYMWxAwRVoWx4n8NAPu
"""

import zipfile
file_list = []

# Open the ZIP file
with zipfile.ZipFile("/content/archive (7).zip", mode="r") as archive:
  archive.extractall()

with zipfile.ZipFile('/content/archive (7).zip', 'r') as zip_ref:
  file_list = zip_ref.namelist()

import librosa
y, sr = librosa.load(file_list[1])

sr

import librosa.display
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 4))
librosa.display.waveshow(y, sr=sr)

import librosa
y1, sr1 = librosa.load(file_list[-10])
import librosa.display
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 4))
librosa.display.waveshow(y1, sr=sr1)

import numpy as np
def feature_extract_mfcc(file_path):
  audio, sr = librosa.load(file_path)
  mfccs = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=80)
  mfcc_mean = np.mean(mfccs, axis=1)
  return mfcc_mean

category = []
for i in file_list:
  if i.split('/')[1] == 'non_dysarthria_male':
    category.append(1)
  elif i.split('/')[1] == 'non_dysarthria_female':
    category.append(1)
  elif i.split('/')[1] == 'dysarthria_female':
    category.append(0)
  elif i.split('/')[1] == 'dysarthria_male':
    category.append(0)

file_list = file_list[1:]

import pandas as pd
data = {
    'Audio': file_list,
    'Category': category
}

df= pd.DataFrame(data)

X = []
categories = df['Category'].tolist()  # Assuming you have a 'Category' column in your dataframe
indices_to_remove = []

for idx, i in enumerate(df['Audio']):
    try:
        X.append(feature_extract_mfcc(i))
    except EOFError:
        print(f"EOFError encountered for file: {i}. Skipping...")
        # Mark the category to be removed later
        indices_to_remove.append(idx)
    except Exception as e:
        print(f"Error encountered for file {i}: {e}. Skipping...")
        indices_to_remove.append(idx)

# Remove corresponding entries in the 'Category' array
categories = [category for idx, category in enumerate(categories) if idx not in indices_to_remove]

# Optionally, print out the categories after removal
print(f"Updated categories: {categories}")

X1 = []
for i in range(len(X)):
  X1.append(X[i].tolist())

import pandas as pd
data = pd.DataFrame(X1)

data['category'] = categories

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(data.drop(columns = 'category'),data['category'], test_size = 0.2, stratify = data['category'])

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dropout, Flatten, Dense, LSTM
from keras.callbacks import ReduceLROnPlateau

# Define the model
model = Sequential()

# CNN layers
model.add(Conv1D(256, kernel_size=5, strides=1, padding='same', activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=5, strides=2, padding='same'))

model.add(Conv1D(256, kernel_size=5, strides=1, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=5, strides=2, padding='same'))

model.add(Conv1D(128, kernel_size=5, strides=1, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=5, strides=2, padding='same'))
model.add(Dropout(0.2))

model.add(Conv1D(64, kernel_size=5, strides=1, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=5, strides=2, padding='same'))

# RNN layers (LSTM)
model.add(LSTM(128, return_sequences=True))  # LSTM layer with return_sequences=True
model.add(LSTM(64))  # Second LSTM layer

# Flatten the output of LSTM and add Dense layers
model.add(Flatten())
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.10))

# Output layer: for binary classification, use 'sigmoid', and for multi-class use 'softmax'
model.add(Dense(2, activation='sigmoid'))  # For binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', 'precision', 'recall'])

# Print model summary
model.summary()

from tensorflow.keras.utils import to_categorical


y_train_one_hot = to_categorical(Y_train, num_classes=2)
y_train_one_hot.shape



y_test_one_hot = to_categorical(Y_test, num_classes=2)
y_test_one_hot.shape

reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.0001)

model.fit(X_train, y_train_one_hot, epochs=20, batch_size=32, validation_data=(X_test, y_test_one_hot), callbacks=[reduce_lr])

Y_pred = model.predict(X_test)

predictions = []
for i in range(len(Y_pred)):
  predictions.append(np.argmax(Y_pred[i]))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, predictions)

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(6, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Dysarthia', 'Non Dysarthia'], yticklabels=['Dysarthia', 'Non Dysarthia'])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

model.save('dysarthria_model.h5')

# Optionally, save the model architecture as JSON
model_json = model.to_json()
with open("model_architecture.json", "w") as json_file:
    json_file.write(model_json)

# Optionally, save only the weights
model.save_weights('model_weights.weights.h5')

print("Model saved successfully.")

model.save('model.keras')

import speech_recognition as sr
from pydub import AudioSegment
import io

# Load MP3 and convert to WAV in-memory
audio_file = "/content/FC01_Session1_0008.mp3"  # Your MP3 file path

# Convert MP3 to WAV in-memory
audio = AudioSegment.from_mp3(audio_file)
wav_io = io.BytesIO()
audio.export(wav_io, format="wav")
wav_io.seek(0)

# Initialize recognizer
recognizer = sr.Recognizer()

# Process the audio file from memory
with sr.AudioFile(wav_io) as source:
    print("Processing audio...")
    audio_data = recognizer.record(source)  # Read the entire audio file

    try:
        # Convert speech to text
        text = recognizer.recognize_google(audio_data)
        print("Transcription:", text)
    except sr.UnknownValueError:
        print("Sorry, could not understand the audio.")
    except sr.RequestError:
        print("Could not request results from Google Speech Recognition service.")

pip install pydub

